"""empty message

Revision ID: 82f8ce32ca1b
Revises: 
Create Date: 2020-06-11 18:19:00.500733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f8ce32ca1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE TODOS SET COMPLETED = FALSE WHERE COMPLETED IS NULL')

    op.alter_column('todos','completed',nullable = False)
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
